# lightning.pytorch==2.5.0.post0
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        mode: "min"
        min_delta: 0.01
        patience: 10
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        mode: "min"
        save_top_k: 2
        save_weights_only: true
        save_last: true
  fast_dev_run: false
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  class_path: models.model_interface.ClassifierInterface
  init_args:
    model_class: models.deformer.Deformer
    model_args:
      skip_pool: false
      symmetric_qk: false
      dropout: 0.5
      num_kernels: 13
      temporal_kernel_size: 64
      mha_depth: 4
      mha_num_heads: 32
      mha_dim_heads: 1024
      mha_hidden_dim: 32
      fc_num_neurons: 256
      fs: 128
      window_length: 10
      num_channel: 32
      num_class: 2
    lr: 1e-3
    loss:
      class_path: torch.nn.modules.loss.CrossEntropyLoss
      init_args:
        weight: null
        size_average: null
        ignore_index: -100
        reduce: null
        reduction: "mean"
    loss_hparams: null
data:
  class_path: datasets.data_interface.DInterface
  init_args:
    dataset_class: datasets.eeg_classify_base_dataset.EegClassifyBaseDataset
    dataset_args:
      root_path: "E:/SuperHuge/derivatives"
      meta_filter_func_args:
        target: binary_leftright
      metadata_fields:
        [
          "dataset_id",
          "subject_id",
          "trial_id",
          "signal_length",
          "num_channel",
          "fs",
          "label",
        ]
    dataloader_args:
      batch_size: 2
optimizer:
  class_path: Adam
  init_args:
    lr: ${model.init_args.lr}
    betas: [0.9, 0.999]
    eps: 1e-08
    weight_decay: 1e-4
lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    monitor: "val_loss"
    mode: "min"
    factor: 0.5
    patience: 5
    verbose: false
    threshold: 1e-4
    threshold_mode: "rel"
    cooldown: 5
    min_lr: 1e-8
    eps: 1e-8
ckpt_path: null
