# lightning.pytorch==2.5.0.post0
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
      log_momentum: false
      log_weight_decay: false
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val_loss
      min_delta: 0.01
      patience: 10
      verbose: false
      mode: min
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: null
      log_rank_zero_only: false
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: null
      monitor: val_loss
      verbose: false
      save_last: true
      save_top_k: 2
      save_weights_only: true
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  fast_dev_run: false
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  class_path: src.models.model_interface.ClassifierInterface
  init_args:
    model_class: src.models.deformer.Deformer
    model_args:
      skip_pool: false
      symmetric_qk: false
      dropout: 0.5
      num_kernels: 13
      temporal_kernel_size: 64
      mha_depth: 4
      mha_num_heads: 32
      mha_dim_heads: 1024
      mha_hidden_dim: 32
      fc_num_neurons: 256
      fs: 128
      window_length: 10
      num_channel: 32
      num_class: 2
    lr: 0.001
    loss:
      class_path: torch.nn.CrossEntropyLoss
      init_args:
        weight: null
        size_average: null
        ignore_index: -100
        reduce: null
        reduction: mean
        label_smoothing: 0.0
    loss_hparams: null
    precision: torch.float32
data:
  class_path: src.datasets.data_interface.DInterface
  init_args:
    dataset_class: src.datasets.eeg_classify_base_dataset.EegClassifyBaseDataset
    dataset_args:
      root_path: E:/SuperHuge/derivatives
      meta_filter_func_args:
      - binary_leftright
      meta_group_func: src.datasets.metadata_processing.loto
      fold_idx: '0'
      n_folds: '5'
      window_length: 10
      fs: 128
      overlap: 1
      metadata_fields:
      - dataset_id
      - subject_id
      - trial_id
      - signal_length
      - num_channel
      - fs
      - label
      transform: null
    dataloader_args:
      batch_size: 2
      num_workers: 8
      persistent_workers: true
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.0001
    amsgrad: false
    foreach: null
    maximize: false
    capturable: false
    differentiable: false
    fused: null
lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    monitor: val_loss
    mode: min
    factor: 0.5
    patience: 5
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 5
    min_lr: 1.0e-08
    eps: 1.0e-08
    verbose: false
ckpt_path: null
