directional_focus_decoding:
  type: classification
  general:
    data:
      init_args:
        dataset_class: src.datasets.eeg_classify_base_dataset.EegClassifyBaseDataset
        dataset_args:
          metadata_fields:
            [
              "dataset_id",
              "subject_id",
              "trial_id",
              "signal_length",
              "num_channel",
              "fs",
              "label",
            ]
          n_folds: 5
  tasks:
    binary_leftright:
      enable: 1
      data:
        init_args:
          dataset_args:
            meta_filter_func_args:
              - binary_leftright
      model:
        init_args:
          model_args:
            num_class: 2
    binary_frontrear:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_filter_func_args:
              - binary_frontrear
      model:
        init_args:
          model_args:
            num_class: 2
    four-class:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_filter_func_args:
              - four-class
      model:
        init_args:
          model_args:
            num_class: 4
    eight-class:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_filter_func_args:
              - eight-class
      model:
        init_args:
          model_args:
            num_class: 8

  cross_validation:
    leave_one_trial_out:
      enable: 1
      data:
        init_args:
          dataset_args:
            meta_group_func: src.datasets.metadata_processing.loto
    leave_one_subject_out:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_group_func: src.datasets.metadata_processing.loso
    leave_one_dataset_out:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_group_func: src.datasets.metadata_processing.lodo
