class_path: datasets.data_interface.DInterface
init_args:
  dataset_class: datasets.eeg_classify_base_dataset.EegClassifyBaseDataset
  dataset_args:
    root_path: "E:/SuperHuge/derivatives"
    meta_filter_func_args:
      target: binary_leftright
    meta_group_func: datasets.metadata_processing.loto
    fold_idx: 1
    n_folds: 5
    window_length: 10
    fs: 128
    overlap: 1
    metadata_fields:
      [
        "dataset_id",
        "subject_id",
        "trial_id",
        "signal_length",
        "num_channel",
        "fs",
        "label",
      ]
    transform: null
  dataloader_args:
    batch_size: 2
    num_workers: 8
    persistent_workers: true
