general:
  window_length:
    1: 1
    10: 1
  fs: 128
  metadata_fields:
    - "dataset_id"
    - "subject_id"
    - "trial_id"
    - "signal_length"
    - "num_channel"
    - "fs"

directional_focus_decoding:
  name: directional_focus_decoding
  type: classification
  dataset_name: eeg_classify_base_dataset
  target:
    binary_leftright:
      enable: 1
      num_class: 2
    binary_frontrear:
      enable: 0
      num_class: 2
    four-class:
      enable: 0
      num_class: 4
    eight-class:
      enable: 0
      num_class: 8

  cross_validation:
    leave_one_trial_out: 1
    leave_one_subject_out: 1
    leave_one_dataset_out: 1
  metadata_fields:
    - "label"

speech_reconstrcution:
  name: speech_reconstruction
  type: regression
  dataset_name: eeg_regression_base_dataset
  target:
    env:
      enable: 0
    mel:
      enable: 0
  cross_validation:
    leave_one_trial_out: 1
    leave_one_subject_out: 1
    leave_one_dataset_out: 1
  metadata_fields:
    - "target_name"
